language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  
env:
  global:
   - secure: "LVZ6C9U1qowU0WVXGmU9JcjuE3DYPUh/II1j8NiT10l0eGtiRhDw799MRcDIyJGr5shnaz2dg1JX72q+hmL/YYXxhXyCMvn5LmqcmBelD8Fpy1YIqfpX5sBHnQfl93w2XmfVA9ZVhzPqxgCQr1b9zCkl4FObP5lUmerkwDo1arKY7k5x3u1r72yK1Qf/U2dZtRqQJhVCqKNboVs94tue2FaKFis5yhRtHfBh7sjj3x+6O2Lk9dnSaXdBOj23sPLLjAqa2LhCny5u4EDiImTHgAytGKTtUXElPYQMM3dj1O5H/I6HQ7ZDUm60uMIOBCBk1kM4Aj5DxtQ57d8ZPP1HbU76IyL+LdQrsv2Jeg8GHC91Et43UP7gb66kdvi+xtnTqkD6ayn5GNoSeHgsg9IAqNsq8Sk/cJ/pWtuc4LL5ohKiJI46kQkNnJ+GDFXHWm0cnZYRZmKYwIHB62GnIf1Vj9GoynetkQcluxM23EpcMlxNdA9T1phk9U2I0enV5C7YY0tLim8R+jynfnnsyOHJuhYwVtrrGHbbT65TQELPcjb6Qlv7VsnC8M0SLSxBXEO5suI+wEwZmpNTO3/BXWLirKp88ssvwqEZqvEermJ4QP7MSqB08W57RZnXPz+Si0Qoq5+/INfXLJgrmK3eTdybzrIcO0EWnYAmLLQPsftX6o4="
   - secure: GBUm1a/UUng/qdfTiddRDp+EE1EdJZBeZOPSsGwTvvGiasQogAUkPeA7aD7gm4SOpjxPovUgL1nmqjkG1ZLXSEJELqL8fKCjZ0EaaggoSwuo2tcKC0Cju2ZqBVCyDwB3SC4eHKhhlUtzvSJ1nr+oSNW/ZvXYhXeCFSxUlRgeQqWwChwXU2rQegVPesx3AWsnNTTn4o9KJziDckH/lR/j/2y6LhF0Z7yU0iQiyBYjJvf6IGWx+xz73K9cLFGdI3UF09gL62yLDBocsJCQXpdRQBirtVnN3NwWreraWLFYXrekxJsH9r9cGfYhtMjyZ4EFqQckK/o2tdKJ9x66bjt6YUQwGA8BgH1zcyyyt7ZeC3bEsCOKx4D2RYVqKuxJ7VKOblpdsbynmow7P+o+VtlJMsGGRNkohLkrBJpsGtsDQtD+OyDeqzyhU5IrkqvHn+nEWeflPaWWO6r8eOa+hXqymwKuwIacqzaxTbEutxX+/Lfp75mpVChYoW8xhYZihURfewVC9Z//sD5w1Bb0pPne+J5bCkzrnb/6aaXAMViwVsdNqm8iS7lvuC2Ba/Y/+w0H6hr+zD2fZgXe4In2IwDOFaXQTg/K7k2i7iCdwUbu5dWLdmJ4P1cXLk5eVWZh6rjSEZp9V7Ghsu+MGHQT4zAPXXb4hzClXdyXGbLzxUvkjcM=
   - secure: MPTf1UXahMxV2kr+NoUWNkaXJ82XEfsYfxFXYlruYI7V68fiG1HraZDojZhaikn6nZGffweewEnGFCtCE8RzyZIyohNTVX7Yk8H+Sg3Om70QtMd1HD/mY/X4Ufla2ubb6AlFDP3xRce6sBVoK8r5c6mDXjSAVfezmO0ibPHRZMcjqfEnPd9RxU7gAadabBOqY6i3qkMmfnMUttbn084fM02H8vtuVrioLMLEq5Yem/MOKk9x0qgQmykh8UuqH7c1bzmwFDDY8PxZvD2GTFCrFMctbXyRTerWbqoWfF2S4xsODLo+pZe+v6UwaLje//vCe22m0GJRUqVgKxjkYE/ud2xHE5mD3Ug6ZgFmvsVZfZNLJbf6LNkTUlNdruJU8xfeLXbTOqGO7OC8cC0+A8c/2Bbk8wgr25+M89sYq8fnWapgd1PmDQqZxbqXNiFCqlfgpHm0R3NogIO54z9aUOPNRaOXXl9cdCvi+/2goVot6yUbmMmnzLKW5iIUuxZl2Bc6ibZMeulCWXrP/RwNGU9i1DjICWyBvjR1RETVd90NdpBQ7I+DxugPz5NmCVLf3rl8Q/tK6ov6n388MwUk62pvw7/FyoseRYbjgmRHzgZ98m5aN3IS4ItUXpUa7sn4Z8OB/WRpl/Qtx6D57oFvbgTGLimvMi29juw3xP42Kodj/+0=

addons:
  coverity_scan:
    project:
      name: "SynthesisProject/server"
      description: "Build submitted via Travis CI"
    notification_email: samuel@opencollab.co.za
    build_command_prepend: "mvn clean"
    build_command:   "mvn -DskipTests=true compile"
    branch_pattern: coverity_scan

after_success:
  - mvn clean deploy --settings settings.xml -DskipTests=true -B
