language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  
env:
  global:
   - secure: "LVZ6C9U1qowU0WVXGmU9JcjuE3DYPUh/II1j8NiT10l0eGtiRhDw799MRcDIyJGr5shnaz2dg1JX72q+hmL/YYXxhXyCMvn5LmqcmBelD8Fpy1YIqfpX5sBHnQfl93w2XmfVA9ZVhzPqxgCQr1b9zCkl4FObP5lUmerkwDo1arKY7k5x3u1r72yK1Qf/U2dZtRqQJhVCqKNboVs94tue2FaKFis5yhRtHfBh7sjj3x+6O2Lk9dnSaXdBOj23sPLLjAqa2LhCny5u4EDiImTHgAytGKTtUXElPYQMM3dj1O5H/I6HQ7ZDUm60uMIOBCBk1kM4Aj5DxtQ57d8ZPP1HbU76IyL+LdQrsv2Jeg8GHC91Et43UP7gb66kdvi+xtnTqkD6ayn5GNoSeHgsg9IAqNsq8Sk/cJ/pWtuc4LL5ohKiJI46kQkNnJ+GDFXHWm0cnZYRZmKYwIHB62GnIf1Vj9GoynetkQcluxM23EpcMlxNdA9T1phk9U2I0enV5C7YY0tLim8R+jynfnnsyOHJuhYwVtrrGHbbT65TQELPcjb6Qlv7VsnC8M0SLSxBXEO5suI+wEwZmpNTO3/BXWLirKp88ssvwqEZqvEermJ4QP7MSqB08W57RZnXPz+Si0Qoq5+/INfXLJgrmK3eTdybzrIcO0EWnYAmLLQPsftX6o4="
   - secure: "Rt4EdClVy5i80ZWyEV8wtPp1ooCYGrBSzbS0vt8hk8HuRxexv8yJ+YLHW4z/7kPy9AfsLjm5ovf1yw7D29xpYik/Uv+QnI4E48MPRNTi5CFHM+iPIwriMcoGxqO8IZwSeuBSlQaHZzYXyaQkUuIO+lvpxmr2FhP+FVu4LkxWPI7vf8yGlVK3qdN0RVLlH6eJhGM3uuXSYBNkXTVQGip1+3ZipdNule+Oz9KVlsDDGBjYzNdgr9wd/r7STne64QSDmJizcSoUUH/NG+rLHnVTf0+btNtjidFhNb3OmmHjj9Ewo4OX1TujX/AYZpLvOD1TN3io2bbGNmhTbAzEGGjWj0Me8nR1cQpOwXa4A2Cw+WJSrvd8xXcTxZe/sIB3jjWi/PCq2widX9hO1TSYFlflnUq1973za3Ls81pDN1UfCwAFTMv7BFURrb1hwGILKwxE1ZocO1mks7iFM2gpJvn/CE4HNaaaMRTcxwj5VGuhF17HUkHfqgcM/O0V3b/nHHd7p6P9Pb9SwvzpQC9mheDy+WjQYyrNKcnfThw3Q+DEE1kYVYy5DenTnQlqc3UlgxcobPQxPDP6s8r+hai4Aa9O+cgU9U5FaKmOXwfGOSx2g1oDPUs/vUUl+VOadnfF2F7UJjrL9TzhMsIuY58e7+tdKFeF8rQNT9r30p8J691JJ+w="
   - secure: "V5EMDnbgu7D9IUfs3bV5k+8QNGi6IwQ8Q5+64IqV0gZRhscAhA+zwjCOnBrfD/SguvPLIPZpfyTuwatMzqz43ZA+wHWyg+CYKgmQndr/Vp15LSz2rKuOFSPZ41POPHY0ssVWBfI8P9GRNGcB+PGpyRtpkHAbL3vLb/Xo0W99WFv15nUDdX43JQpdj1RoRep/Uy629s1OYjBanbZrR5iS1PBLs3pzhJxsVS2YGGpXfsXJNv9xUz6G0eSIvK2IwV6DsEFf8h7mZnpkhUgTl6RREOwjKpzwMeDY5V94lTKlV15qA53uLgIDAQpkK6KmkbcJGpFA7MlYS1cbDH/oNRcbAzUQglqiWAd2YlhvrPOoDHNn6QLV1luJcqWmQKSCsCq/ybD3vaKnXCPD31ZOxSggNTy0Ewz+l2cw4z2qFZvjl6Mxvg9001ooD/jZxAsDtMAkafsUkhRoifETG7v/uotCCHfOZrT4YifjNYh9jsI/sOeRRkxOsCxe0JuyCbIizspUtvcRSeSgZGG39ZSODkmelsk0n1mGD1Y0nMJJrRvH89lRkm3n6ABjEKqN9aWESy30kT+8Ga9bTlr+5uLf6/exYTOv+fXUifLYsL0Wb/Ackaq9P6sal174bWJ8YaDfDP7BQAgvE6oMNgwqIag054rO2CgDyb8Js55CaXdfx3VMN+0="

addons:
  coverity_scan:
    project:
      name: "SynthesisProject/server"
      description: "Build submitted via Travis CI"
    notification_email: samuel@opencollab.co.za
    build_command_prepend: "mvn clean"
    build_command:   "mvn -DskipTests=true compile"
    branch_pattern: coverity_scan

after_success:
  - mvn clean deploy --settings settings.xml -DskipTests=true -B
