language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "WBnrJRHlrmPcb8ZpKovUE5EqiISWREvyUeGEvv90WvNDRfAf2M8S9EPD/NfYboQY5TdT+NFZq4IIvinP7LBEvY3mNzomFf2d5apCqf11YT0XiIab0TXzs3OKDjd+ydIDCCG6eIkwMzZyS9uEHkgEZjBMpxzwC4EiWXh1IzX5aVARV9B+wtECrP+Vhq6JhxXoBvKK3+21SsI/y7tDhS4bGg2JECRP8ZitylUnipzlo9CklHosYxJps5scd5kfn4DDneBzLyZPxfOm35jXdvFXHLS+t4QuQkNDh0X1t6LDu2PU/xDbocOGpUuQzWTnwnDdcQaCXk/sNqLrv4F0mYgn92JQcgLGfXNbRBZXOzfXR4Y9TXibLY7a8wVSjP2jaacF+7k/mYf7h8GN5yz2txqpU7p/Gw/VC9V9yQ61U5FMg12Ao2Wz9jfPvegJzMAK4RADF4T7Al6fE0OQG1xroTc0r8Rf/Na8D2lVUiP7cFtUUzheqZx/4lA57kHFJI7J9HiQO82teTBxDJruJusAs5l93nJmJrhhJUs4+xMu4WPpxSLUbaN/uM7ddgwuhbUwq+GYFApd7vxFBn7mu9psnPDaauFO3cjlQ6yNdr3nH5z19cuXF/g1xD3mYSR0xfUIHd1Bk54DiuCmdJRMYtz5ZpGlhVK4F9scjk8S3wYXWXGoT3U="

addons:
  coverity_scan:
    project:
      name: "SynthesisProject/server"
      description: "Build submitted via Travis CI"
    notification_email: samuel@opencollab.co.za
    build_command_prepend: "mvn clean"
    build_command:   "mvn -DskipTests=true compile"
    branch_pattern: coverity_scan  
